### ISSUE TITLE
Bot do not start

### ISSUE THREAD

**Issue by D3sTeptu** [zhon12345/Ticket-Bot#17]
```

(node:2408) UnhandledPromiseRejectionWarning: Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\zEU.DESKTOP-H3MLTQG\Desktop\Ticket-Bot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:258:15)
    at async Client.login (C:\Users\zEU.DESKTOP-H3MLTQG\Desktop\Ticket-Bot-main\node_modules\discord.js\src\client\Client.js:223:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by D3sTeptu** [comment]
i fixed
