### ISSUE TITLE
error

### ISSUE THREAD

**Issue by caipcaipie** [zhon12345/Ticket-Bot#31]
/home/runner/Ticket-Bot/node_modules/discord.js/src/rest/RequestHandler.js:154
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^

DiscordAPIError: Invalid Form Body
embed.footer.icon_url: Scheme "null" is not supported. Scheme must be one of ('http', 'https').
embeds[0].footer.icon_url: Scheme "null" is not supported. Scheme must be one of ('http', 'https').
    at RequestHandler.execute (/home/runner/Ticket-Bot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/runner/Ticket-Bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/channels/985160642325532693/messages',
  code: 50035,
  httpStatus: 400
}

**Comment by zhon12345** [comment]
your bot does not has a custom icon, that's causing the issue
